FROM centos:centos7.3.1611

# 环境变量
ENV JAVA_HOME /usr/lib/jdk-1.8.0-232 
ENV CLASSPATH ${JAVA_HOME}/jre/lib:${JAVA_HOME}/lib
ENV PATH ${JAVA_HOME}/bin:$PATH:/opt/apache-maven-3.5.4/bin

# 更新/安装必要软件
RUN set -x \
    && yum clean all \
    && yum makecache \
    && yum update  -y \
    && yum install -y wget \
    && cd /bigdata/ambari-2.7.4-sourcecode \
    # && wget http://mirror.bit.edu.cn/centos/7.7.1908/os/x86_64/Packages/net-tools-2.0-0.25.20131004git.el7.x86_64.rpm \
    && yum install -y vim curl net-tools telnet procps gzip python2.7 python-pip python-dev python-devel.x86_64 git rpm-build npm gcc-c++

# 安装 Open JDK
RUN set -x \
  && wget ${HD1_REPO_URL}/jdk/jdk-1.8.0-232.tar.gz  -O /tmp/jdk-1.8.0-232.tar.gz \
  && tar -zxvf /tmp/jdk-1.8.0-232.tar.gz -C /usr/lib/ \
  && chmod -R 755 ${JAVA_HOME} \
  && java -version \
  && mkdir -p /usr/share/java \
  && cd /usr/share/java \
  && wget http://10.221.129.22/InspurHD1.0/jdk/mysql-connector-java-5.1.48.jar

# 安装 Maven
RUN set -x \
  && cd /opt \
  && wget http://mirrors.hust.edu.cn/apache/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz \
  && tar -zxvf apache-maven-3.5.4-bin.tar.gz \
  && rm -f /opt/apache-maven-3.5.4/conf/settings.xml
